/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tchimgescom.Client.Magasin;


import tchimgescom.Paquet;

/**
 *
 * @author hp
 */
public class Magasin_Vue extends javax.swing.JInternalFrame {
    String ancienCode ;

    private Magasin_Ctrl Ctrl;
    
    public Magasin_Vue() {
        initComponents();     
    }
    
    public Magasin_Vue(Magasin_Ctrl Ctrl) {
        this.Ctrl=Ctrl;
        initComponents();
        initialiser(true);        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCategorie = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldCodeCategorie = new javax.swing.JTextField();
        jTextFieldLibelle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonNouveau = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonFermer = new javax.swing.JButton();
        jButtonRafraichir = new javax.swing.JButton();
        jButtonAjouter = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Famille de produits");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTableCategorie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code famille Produit", "Libellé"
            }
        ));
        jTableCategorie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCategorieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCategorie);
        jTableCategorie.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTextFieldCodeCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeCategorieActionPerformed(evt);
            }
        });

        jTextFieldLibelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLibelleActionPerformed(evt);
            }
        });

        jLabel1.setText("Code famille de produit");

        jLabel2.setText("Libellé");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(50, 50, 50)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldCodeCategorie, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                        .addComponent(jTextFieldLibelle))
                    .addGap(35, 35, 35)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCodeCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(120, 572));

        jButtonNouveau.setText("Nouveau");
        jButtonNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNouveauActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        jButtonFermer.setText("Fermer");
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });

        jButtonRafraichir.setText("Rafraichir");
        jButtonRafraichir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRafraichirActionPerformed(evt);
            }
        });

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRafraichir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButtonRafraichir)
                .addGap(18, 18, 18)
                .addComponent(jButtonNouveau)
                .addGap(14, 14, 14)
                .addComponent(jButtonAjouter)
                .addGap(18, 18, 18)
                .addComponent(jButtonModifier)
                .addGap(18, 18, 18)
                .addComponent(jButtonSupprimer)
                .addGap(18, 18, 18)
                .addComponent(jButtonFermer)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initialiser(boolean Raf){
        jTextFieldCodeCategorie.setText("");
        jTextFieldLibelle.setText("");
        comportementbouton(Raf); 
        if (Raf){
            actualiser();
        }
    }
    private void comportementbouton(boolean Raf)
    {
        jButtonAjouter.setEnabled(Raf);
        jButtonModifier.setEnabled(!Raf);
        jButtonSupprimer.setEnabled(!Raf);  
    }
    
    private void nouveau(){
        initialiser(true);
    }
    
    private void actualiser()
    {
        String[] Titres={"Code", "Libellé"};
        Ctrl.rafraichir(Titres,jTableCategorie);
    }
        
    private void selectionner()
    {
        int row=jTableCategorie.getSelectedRow();
        if (row>=0){
            jTextFieldCodeCategorie.setText(jTableCategorie.getValueAt(row,0).toString());
            jTextFieldLibelle.setText(jTableCategorie.getValueAt(row,1).toString());

            ancienCode=jTextFieldCodeCategorie.getText();
            comportementbouton(false);
        } 
    }        
    
    private void ajouter(){
        String[] parametre={jTextFieldCodeCategorie.getText(),jTextFieldLibelle.getText()};
        Paquet result=Ctrl.ajouter(parametre);
        if (result.getOk()){
            initialiser(true);
        }
    }
    
    private void modifier(){
        String[] parametre={jTextFieldCodeCategorie.getText(),jTextFieldLibelle.getText(), ancienCode};
        Paquet result=Ctrl.modifier(parametre);
        if (result.getOk()){
            initialiser(true);
        }
    }
    
    private void supprimer(){
        String[] parametre={ancienCode};
        Paquet result=Ctrl.supprimer(parametre);
        if (result.getOk()){
            initialiser(true);
        }
    }
    

    

 
    private void jButtonNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNouveauActionPerformed
        // TODO add your handling code here:
        initialiser(true);
    }//GEN-LAST:event_jButtonNouveauActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        // TODO add your handling code here:
        modifier();
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        // TODO add your handling code here:
        supprimer();
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonFermerActionPerformed

    private void jButtonRafraichirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRafraichirActionPerformed
        // TODO add your handling code here:
        actualiser();
    }//GEN-LAST:event_jButtonRafraichirActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        // TODO add your handling code here:
        ajouter();
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jTableCategorieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCategorieMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        int NbClick= evt.getClickCount();
        if (NbClick==2){
           selectionner(); 
        }
    }//GEN-LAST:event_jTableCategorieMouseClicked

    private void jTextFieldLibelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLibelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLibelleActionPerformed

    private void jTextFieldCodeCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodeCategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodeCategorieActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonNouveau;
    private javax.swing.JButton jButtonRafraichir;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCategorie;
    private javax.swing.JTextField jTextFieldCodeCategorie;
    private javax.swing.JTextField jTextFieldLibelle;
    // End of variables declaration//GEN-END:variables
}
