/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tchimgescom.Client.Categorie;

import java.awt.Dimension;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import tchimgescom.Paquet;
import tchimgescom.Res;

/**
 *
 * @author Aymar NLEND
 */
public class Categorie_Vue_Fiche extends javax.swing.JDialog {
    private Categorie_Ctrl Ctrl;
    private Object[] donnees;
    private String op;
    String ancienCode;
    
    /**
     * Creates new form FenFamilleProduit_Fiche
     * @param parent
     * @param modal
     */
    public Categorie_Vue_Fiche(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        Dimension dlgSize = new Dimension(800, 600);
        setSize(dlgSize);
    }

    public Categorie_Vue_Fiche(java.awt.Frame parent, Categorie_Ctrl Ctrl, Object[] donnees) {
        super(parent, true);
        this.Ctrl = Ctrl;
        this.donnees=donnees;        
        initComponents();
        dimensionnerFenetre();
        initialiser();
        
    }

    public Categorie_Vue_Fiche(javax.swing.JDialog parent, Categorie_Ctrl Ctrl, Object[] donnees) {
        super(parent, true);
        this.Ctrl = Ctrl;
        this.donnees=donnees;    
        initComponents();
        dimensionnerFenetre();
        initialiser();
    }
    
    private void dimensionnerFenetre()
    {
        this.pack();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        Dimension dlgSize = new Dimension(800, 600);
        setSize(dlgSize);
    }
    private void initialiser()
    {
        if (donnees.length > 0 )
        {
            op = "M";
            int i = 0;
            jTextFieldCodeCategorie.setText(Res.ft_Chaine(donnees[i++]));
            jTextFieldLibelle.setText(Res.ft_Chaine(donnees[i++]));
        }
        else
        {
            op = "A";
            jTextFieldCodeCategorie.setText("");
            jTextFieldLibelle.setText("");
        }
        ancienCode = jTextFieldCodeCategorie.getText();
    }
    
    
    private void ajouter(){
        String[] parametre={jTextFieldCodeCategorie.getText(),jTextFieldLibelle.getText()};
        Paquet result=Ctrl.ajouter(parametre);
        if (result.getOk()){
            initialiser();
        }
    }
    
    private void modifier(){
        Object[] parametre={jTextFieldCodeCategorie.getText(),jTextFieldLibelle.getText(), ancienCode};
        Paquet result=Ctrl.modifier(parametre);
        if (result.getOk()){
            initialiser();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLibelle = new javax.swing.JTextField();
        jTextFieldCodeCategorie = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonEnregistrer = new javax.swing.JButton();
        jButtonFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Code ");

        jLabel2.setText("Libellé");

        jTextFieldLibelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLibelleActionPerformed(evt);
            }
        });

        jTextFieldCodeCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeCategorieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCodeCategorie, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jTextFieldLibelle))
                .addGap(16, 16, 16))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(321, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTextFieldCodeCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel1)
                    .addContainerGap(67, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(128, 282));

        jButtonEnregistrer.setText("Enregistrer");
        jButtonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistrerActionPerformed(evt);
            }
        });

        jButtonFermer.setText("Fermer");
        jButtonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFermer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEnregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonEnregistrer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFermer)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLibelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLibelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLibelleActionPerformed

    private void jTextFieldCodeCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodeCategorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodeCategorieActionPerformed

    private void jButtonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrerActionPerformed
         donnees= new Object[]{jTextFieldCodeCategorie.getText(),jTextFieldLibelle.getText(), ancienCode};
        if (op.equals("A")) {
            ajouter();
        } else {
            modifier();
        }
        
        if (op.equals("A"))
        {
            if (Ctrl.ajouter(donnees).getOk())
            {
                op = "M";
            }
        }
        else
        {
            Ctrl.modifier(donnees);
        }
    }//GEN-LAST:event_jButtonEnregistrerActionPerformed

    private void jButtonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonFermerActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnregistrer;
    private javax.swing.JButton jButtonFermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldCodeCategorie;
    private javax.swing.JTextField jTextFieldLibelle;
    // End of variables declaration//GEN-END:variables
}
